version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/client-liveto/client

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: ../../../scripts/before_install.sh
      timeout: 2000
      runas: root
  AfterInstall:
    - location: ../../../scripts/after_install.sh
      timeout: 2000
      runas: root
  ApplicationStart:
    - location: ../../../scripts/app_start.sh
      timeout: 2000
      runas: root